image:
  landing:
    name: landing
    repository: nginx
    pullPolicy: IfNotPresent
    tag: latest
    containerPort: 80
    servicePort: 80
  backend:
    name: backend
    repository: rahulsinha1908/stock-backend-app
    pullPolicy: IfNotPresent
    tag: v8
    containerPort: 3001
    servicePort: 80
  pythonApp:
    name: python
    repository: rahulsinha1908/stock-python-app
    pullPolicy: IfNotPresent
    tag: v11
    containerPort: 3002
    servicePort: 80
  pythonScrapper:
    name: python-scrapper
    repository: rahulsinha1908/stock-python-scrapper
    pullPolicy: IfNotPresent
    tag: v3

imagePullSecrets: []

ingress:
  enabled: true
  name: "stock-app-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: bigandsmallapps.com
      paths:
        - path: "/"
          serviceName: "landing-service"
          servicePort: 80
    - host: api.bigandsmallapps.com
      paths:
        - path: "/api/v1"
          serviceName: "backend-service"
          servicePort: 80
  tls:
    - secretName: stock-app-tls-secret
      hosts:
        - bigandsmallapps.com
        - api.bigandsmallapps.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
