image:
  fallonBackend:
    name: fallon-backend
    repository: rahulsinha1908/fallon-backend
    pullPolicy: IfNotPresent
    tag: latest
    containerPort: 4201
    servicePort: 80
  trade:
    name: backend-trade
    repository: rahulsinha1908/stock-trade
    pullPolicy: IfNotPresent
    tag: latest
    containerPort: 3001
    servicePort: 80
  tradeSocket:
    name: backend-trade-socket
    repository: rahulsinha1908/stock-trade-socket
    pullPolicy: IfNotPresent
    tag: latest
    containerPort: 3001
    servicePort: 80
  fallonFrontend:
    name: fallon-frontend
    repository: rahulsinha1908/fallon-frontend
    pullPolicy: IfNotPresent
    tag: v11
    containerPort: 80
    servicePort: 80
  frontend:
    name: frontend
    repository: rahulsinha1908/stock-frontend
    pullPolicy: IfNotPresent
    tag: v31
    containerPort: 80
    servicePort: 80
  backend:
    name: backend
    repository: rahulsinha1908/stock-backend-app
    pullPolicy: IfNotPresent
    tag: v51
    containerPort: 3001
    servicePort: 80
  pythonApp:
    name: python
    repository: rahulsinha1908/stock-python-app
    pullPolicy: IfNotPresent
    tag: v28
    containerPort: 3002
    servicePort: 80
  pythonScrapper:
    name: python-scrapper
    repository: rahulsinha1908/stock-python-scrapper
    pullPolicy: IfNotPresent
    tag: v27

imagePullSecrets: []

ingress:
  enabled: true
  name: "stock-app-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: bigandsmallapps.com
      paths:
        - path: "/"
          serviceName: "frontend-service"
          servicePort: 80
    - host: api.bigandsmallapps.com
      paths:
        - path: "/api/v1"
          serviceName: "backend-service"
          servicePort: 80
        - path: "/trade"
          serviceName: "backend-trade-service"
          servicePort: 80
        - path: "/socket"
          serviceName: "backend-trade-socket-service"
          servicePort: 80
        - path: "/fallon"
          serviceName: "fallon-backend-service"
          servicePort: 80
    - host: fallon.bigandsmallapps.com
      paths:
        - path: "/"
          serviceName: "fallon-frontend-service"
          servicePort: 80
  tls:
    - secretName: stock-app-tls-secret
      hosts:
        - bigandsmallapps.com
        - api.bigandsmallapps.com
        - fallon.bigandsmallapps.com
        - fallonapi.bigandsmallapps.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
