apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.trade.name }}-deployment
  labels:
    app: {{ .Values.image.trade.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.image.trade.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.trade.name }}
    spec:
      containers:
      - name: {{ .Values.image.trade.name }}
        image: {{ .Values.image.trade.repository }}:{{ .Values.image.trade.tag }}
        ports:
        - containerPort: {{ .Values.image.trade.containerPort }}
        env:
        - name: env
          value: prod
        - name: PYTHON_BASE_URL
          value: "http://10.245.184.190"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.trade.name }}-service
  labels:
    app: {{ .Values.image.trade.name }}
spec:
  selector:
    app: {{ .Values.image.trade.name }}
  ports:
    - port: {{ .Values.image.trade.servicePort }}
      targetPort: {{ .Values.image.trade.containerPort }}
      protocol: TCP
      name: http
  