name: Update and refresh Helm

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  push:
    branch: master

env:
  HELM_NAMESPACE: stocks
  HELM_APP_NAME: stocks-app-helm
  HELM_REPO: https://zvoid-stocks.github.io/helm/
  HELM_REPO_NAME: stock-app-helm
  # KUBE_CONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    name: Deployment
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v22.2
      with:
        files: ./deploy-configs/**
        separator: " -f "


    - name: List all changed files
      run: |
        # echo "Checking this out: -f ${{ steps.changed-files.outputs.all_changed_files }}"
        if [ ${{ steps.changed-files.outputs.any_changed }} == 'true' ]
        then
          echo "-f ${{ steps.changed-files.outputs.all_changed_files }}"
        else
          echo "Nothing changed"
        fi

    # - name: Connect to kubernetes
    #   uses: azure/k8s-set-context@v2
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.KUBECONFIG }}
    # - name: Helm Upgrade
    #   run: |
    #     helm upgrade -n $HELM_NAMESPACE $HELM_APP_NAME $HELM_REPO_NAME --repo $HELM_REPO --reuse-values
